-- Insert sample youth groups
INSERT INTO youth_groups (name, parish, address, city, age_range, meeting_day, meeting_time, description, contact_person, contact_email, contact_phone, type, members_count) VALUES
('St. Mary''s Youth Ministry', 'St. Mary''s Catholic Church', '123 Faith Street', 'Ahmedabad', '14-18', 'Sunday', '4:00 PM - 6:00 PM', 'A vibrant youth group focused on building a strong Catholic community through prayer, service, and fellowship.', 'Fr. Thomas', 'youth@stmarys.org', '+91 98765 43210', ARRAY['Prayer', 'Service', 'Social'], 45),
('Sacred Heart Young Adults', 'Sacred Heart Cathedral', '456 Divine Avenue', 'Ahmedabad', '18-25', 'Wednesday', '7:00 PM - 9:00 PM', 'A group for young adults seeking to deepen their faith through Bible study, adoration, and community outreach.', 'Sarah Joseph', 'youngadults@sacredheart.org', '+91 87654 32109', ARRAY['Bible Study', 'Adoration', 'Outreach'], 32),
('Holy Family Teen Ministry', 'Holy Family Church', '789 Blessing Road', 'Ahmedabad', '13-17', 'Saturday', '5:30 PM - 7:30 PM', 'A teen-focused ministry that combines faith formation with fun activities to help young Catholics grow in their faith journey.', 'Maria D''Souza', 'teens@holyfamily.org', '+91 76543 21098', ARRAY['Faith Formation', 'Social', 'Music'], 28),
('St. Joseph''s College Ministry', 'St. Joseph''s Church', '321 Grace Lane', 'Mumbai', '18-22', 'Friday', '6:00 PM - 8:00 PM', 'A college-focused ministry that helps students balance academic life with spiritual growth through study groups and retreats.', 'Fr. Michael', 'college@stjosephs.org', '+91 98765 12345', ARRAY['Study Groups', 'Retreats', 'Prayer'], 38),
('Our Lady of Mercy Youth', 'Our Lady of Mercy Parish', '654 Hope Street', 'Delhi', '15-19', 'Thursday', '5:00 PM - 7:00 PM', 'A dynamic youth group that focuses on social justice, community service, and building lasting friendships in Christ.', 'Sister Catherine', 'youth@ourladyofmercy.org', '+91 87654 98765', ARRAY['Social Justice', 'Service', 'Fellowship'], 42);

-- Insert sample bible verses for the next few days
INSERT INTO bible_verses (verse, reference, reflection, date) VALUES
('For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, to give you hope and a future.', 'Jeremiah 29:11', 'God has a beautiful plan for your life. Even when things seem uncertain, trust that He is working all things together for your good. Take time today to pray about your future and listen for His guidance.', CURRENT_DATE),
('Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.', 'Joshua 1:9', 'Courage doesn''t mean the absence of fear, but moving forward despite it. God promises to be with you in every challenge you face. What situation in your life needs God''s courage today?', CURRENT_DATE + INTERVAL '1 day'),
('Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.', 'Proverbs 3:5-6', 'Sometimes we try to figure everything out on our own, but God''s wisdom is far greater than ours. Surrender your plans to Him and trust His timing. He will guide your steps.', CURRENT_DATE + INTERVAL '2 days'),
('The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.', 'Zephaniah 3:17', 'You are deeply loved by God! He doesn''t just tolerate you - He delights in you and rejoices over you. When you feel unloved or unworthy, remember that the Creator of the universe sings over you with joy.', CURRENT_DATE + INTERVAL '3 days'),
('And we know that in all things God works for the good of those who love him, who have been called according to his purpose.', 'Romans 8:28', 'Even in difficult times, God is working behind the scenes for your good. This doesn''t mean everything that happens is good, but that God can bring good out of any situation when we trust Him.', CURRENT_DATE + INTERVAL '4 days');

-- Note: Sample prayer requests, events, and journal entries will be created by users through the application
-- This ensures proper user association and realistic data flow
