-- Insert comprehensive sample data for production

-- Insert sample bible verses for the next 30 days
INSERT INTO bible_verses (verse, reference, translation, reflection, theme, season, date, discussion_questions, prayer_suggestion) VALUES
('For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, to give you hope and a future.', 'Jeremiah 29:11', 'NIV', 'God has a beautiful plan for your life. Even when things seem uncertain, trust that He is working all things together for your good. Take time today to pray about your future and listen for His guidance.', 'Hope', 'Ordinary Time', CURRENT_DATE, ARRAY['What plans do you think God has for your life?', 'How can you trust God more in uncertain times?'], 'Lord, help me trust in Your perfect plan for my life.'),

('Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.', 'Joshua 1:9', 'NIV', 'Courage doesn''t mean the absence of fear, but moving forward despite it. God promises to be with you in every challenge you face. What situation in your life needs God''s courage today?', 'Courage', 'Ordinary Time', CURRENT_DATE + INTERVAL '1 day', ARRAY['What fears are holding you back?', 'How has God shown His presence in difficult times?'], 'God, give me courage to face my fears with You by my side.'),

('Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.', 'Proverbs 3:5-6', 'NIV', 'Sometimes we try to figure everything out on our own, but God''s wisdom is far greater than ours. Surrender your plans to Him and trust His timing. He will guide your steps.', 'Trust', 'Ordinary Time', CURRENT_DATE + INTERVAL '2 days', ARRAY['What areas of your life do you need to surrender to God?', 'How can you practice trusting God daily?'], 'Help me trust You completely, Lord, and not rely on my own understanding.'),

('The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.', 'Zephaniah 3:17', 'NIV', 'You are deeply loved by God! He doesn''t just tolerate you - He delights in you and rejoices over you. When you feel unloved or unworthy, remember that the Creator of the universe sings over you with joy.', 'God''s Love', 'Ordinary Time', CURRENT_DATE + INTERVAL '3 days', ARRAY['How does it feel to know God delights in you?', 'What would change if you truly believed God rejoices over you?'], 'Thank You, Lord, for Your incredible love and delight in me.'),

('And we know that in all things God works for the good of those who love him, who have been called according to his purpose.', 'Romans 8:28', 'NIV', 'Even in difficult times, God is working behind the scenes for your good. This doesn''t mean everything that happens is good, but that God can bring good out of any situation when we trust Him.', 'God''s Sovereignty', 'Ordinary Time', CURRENT_DATE + INTERVAL '4 days', ARRAY['How have you seen God work good from difficult situations?', 'What current challenge needs God''s transforming power?'], 'Lord, help me see Your good work even in difficult circumstances.'),

('Cast all your anxiety on him because he cares for you.', '1 Peter 5:7', 'NIV', 'God invites you to bring all your worries to Him - not because He needs to know about them, but because carrying them alone weighs you down. He cares deeply about every concern in your heart.', 'Peace', 'Ordinary Time', CURRENT_DATE + INTERVAL '5 days', ARRAY['What anxieties do you need to give to God today?', 'How can you practice casting your cares on Him daily?'], 'Jesus, I give You all my worries and trust in Your loving care.'),

('I can do all this through him who gives me strength.', 'Philippians 4:13', 'NIV', 'This verse isn''t about achieving anything you want, but about finding strength in Christ for whatever He calls you to do. His strength is perfect in your weakness.', 'Strength', 'Ordinary Time', CURRENT_DATE + INTERVAL '6 days', ARRAY['What challenges do you need Christ''s strength for?', 'How has God strengthened you in the past?'], 'Christ, be my strength in all that You call me to do.');

-- Insert sample youth groups across different cities
INSERT INTO youth_groups (name, parish, address, city, state, age_range, meeting_day, meeting_time, description, contact_person, contact_email, contact_phone, type, activities, requirements, members_count, max_capacity, created_by) VALUES
('St. Mary''s Youth Ministry', 'St. Mary''s Catholic Church', '123 Faith Street', 'Ahmedabad', 'Gujarat', '14-18', 'Sunday', '4:00 PM - 6:00 PM', 'A vibrant youth group focused on building a strong Catholic community through prayer, service, and fellowship. We meet every Sunday for faith sharing, games, and community service projects.', 'Fr. Thomas Abraham', 'youth@stmarys.org', '+91 98765 43210', ARRAY['Prayer', 'Service', 'Social'], ARRAY['Weekly faith sharing', 'Monthly service projects', 'Youth retreats', 'Sports activities'], ARRAY['Regular attendance', 'Parental consent for minors'], 45, 60, NULL),

('Sacred Heart Young Adults', 'Sacred Heart Cathedral', '456 Divine Avenue', 'Mumbai', 'Maharashtra', '18-25', 'Wednesday', '7:00 PM - 9:00 PM', 'A group for young adults seeking to deepen their faith through Bible study, adoration, and community outreach. Perfect for college students and young professionals.', 'Sarah Joseph', 'youngadults@sacredheart.org', '+91 87654 32109', ARRAY['Bible Study', 'Adoration', 'Outreach'], ARRAY['Weekly Bible study', 'Monthly adoration nights', 'Community outreach', 'Career guidance'], ARRAY['Age 18-25', 'Commitment to weekly meetings'], 32, 40, NULL),

('Holy Family Teen Ministry', 'Holy Family Church', '789 Blessing Road', 'Bangalore', 'Karnataka', '13-17', 'Saturday', '5:30 PM - 7:30 PM', 'A teen-focused ministry that combines faith formation with fun activities to help young Catholics grow in their faith journey. Music, drama, and creative arts are integral parts of our ministry.', 'Maria D''Souza', 'teens@holyfamily.org', '+91 76543 21098', ARRAY['Faith Formation', 'Social', 'Music'], ARRAY['Music ministry', 'Drama performances', 'Faith formation classes', 'Social events'], ARRAY['Age 13-17', 'Regular participation'], 28, 35, NULL),

('St. Joseph''s College Ministry', 'St. Joseph''s Church', '321 Grace Lane', 'Delhi', 'Delhi', '18-22', 'Friday', '6:00 PM - 8:00 PM', 'A college-focused ministry that helps students balance academic life with spiritual growth through study groups and retreats. We provide a supportive community for Catholic college students.', 'Fr. Michael Rodriguez', 'college@stjosephs.org', '+91 98765 12345', ARRAY['Study Groups', 'Retreats', 'Prayer'], ARRAY['Study support groups', 'Spiritual retreats', 'Prayer meetings', 'Academic guidance'], ARRAY['College enrollment', 'Catholic faith'], 38, 50, NULL),

('Our Lady of Mercy Youth', 'Our Lady of Mercy Parish', '654 Hope Street', 'Chennai', 'Tamil Nadu', '15-19', 'Thursday', '5:00 PM - 7:00 PM', 'A dynamic youth group that focuses on social justice, community service, and building lasting friendships in Christ. We actively engage in helping the less fortunate in our community.', 'Sister Catherine Francis', 'youth@ourladyofmercy.org', '+91 87654 98765', ARRAY['Social Justice', 'Service', 'Fellowship'], ARRAY['Community service', 'Social justice advocacy', 'Fellowship activities', 'Leadership training'], ARRAY['Age 15-19', 'Heart for service'], 42, 55, NULL);

-- Note: Sample users, prayer requests, events, and journal entries will be created through the application
-- This ensures proper authentication flow and realistic user-generated content
